### ISSUE TITLE
Agent v1.x not expanding variables like your extension

### ISSUE THREAD

**Issue by jdshkolnik** [jessehouwing/vsts-variable-tasks#17]
I think deprecating your task might be too hasty. I'm on TFS 2017 with agent version 1.105.7 and have a build definition with the following variables defined:

- Major = 1
- Minor = 0
- Patch = 0
- UniqueAppend = `_$(Major)$(Minor)$(Patch)_$(Build.SourceVersion)_build$(Build.BuildId)`

If I first run your expand variables task, using $(UniqueAppend) in a task parameter comes out like "`_160_79103_build6029`". If I disable your task, I get "`_$(Major)$(Minor)$(Patch)_$(Build.SourceVersion)_build$(Build.BuildId)`"

**Comment by jessehouwing** [comment]
Agent 2.0 does expansion. It's the default proposed agent on vsts and TFS
2015.3 and 2017.

I need to do something here because the implementation of the expand task
uses an undocumented method which no longer works on 2.0 and I can't make
it work.

I'll leave it in for the considerable future, but won't do support on it
anymore. Moving to agent 2.0 for my tasks.

**Comment by jdshkolnik** [comment]
That's odd. I know how to update them manually but I would've expected them to be the latest versino post-upgrade yet my agents are 1.105.7 even after I click "Update all agents" in TFS admin.

**Comment by jessehouwing** [comment]
They don't upgrade to new major versions automatically due to these kinds
of breaking changes.

**Comment by jessehouwing** [comment]
You need to do a fresh install of the 2.0 agent to jump the major version
boundary.

**Comment by jdshkolnik** [comment]
Thanks.
